name: timeflux-eego-env
dependencies:
    - python>=3.6
    - numpy>=1.16
    - pybind11==2.2.4
    - pytest
    - pip
    - pip:
        - frozendict
        - git+https://github.com/timeflux/timeflux
        - pytest-runner
        - git+https://github.com/timeflux/timeflux_ui
